### 1. Numpy N-Dimensional Array

In [2]:
import numpy as np

- ndarray(numpy array)와 list의 차이

In [3]:
l = [1, 2, 3, 4, 5]
l = [i * i for i in l]
l

[1, 4, 9, 16, 25]

In [4]:
n = np.array([1, 2, 3, 4, 5], dtype=int)
n

array([1, 2, 3, 4, 5])

In [5]:
n = np.square(n)
n

array([ 1,  4,  9, 16, 25])

- 1차원 배열(Vactor)

In [6]:
a = np.array((1,2,3,4,5,6,7,8,9,10))
type(a)

numpy.ndarray

In [8]:
a.dtype, a.shape, a.ndim, a.size
# dtype : data type (정수를 32bt로 표현했다)
# shape : 1차원 : 값의 갯수 ( ,는 tuple type이기 때문에 )
# ndim : 1차원
# size : 값의 갯수

(dtype('int32'), (10,), 1, 10)

In [9]:
# 벡터화 연산
a * 2           # 데이터를 각각 2배씩 연산해줌

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
c = 2 * a + b           # [1, 2, 3] -> [2, 4, 6] -> [12, 24, 36]
c

array([12, 24, 36])

In [11]:
a == 2, b > 10

(array([False,  True, False]), array([False,  True,  True]))

- 2차원 배열(Matrix)

In [14]:
c = np.array([[1,2,3], [4,5,6]])        # np.arange(1, 7).reshape(2, 3)
print(c)                                # array() 가 빠진 형태
c

[[1 2 3]
 [4 5 6]]


array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
c.dtype, c.shape, c.ndim, c.size
# shape : 행, 열
# ndim : 2차원

(dtype('int32'), (2, 3), 2, 6)

- 3차원 배열(Tensor)

In [16]:
t = np.arange(1, 25).reshape(2, 3, 4)
t

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [20]:
t.dtype, t.shape, t.ndim, t.size
# shape : 평면(plane), 행(row), 열(colunm)
# ndim : 3차원

(dtype('int32'), (2, 3, 4), 3, 24)

- 배열의 인덱싱

In [21]:
a

array([1, 2, 3])

In [23]:
a[0], a[1], a[2], a[-1]

(1, 2, 3, 3)

In [25]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
c[0][0], c[0,0], c[-1,0], c[1,2]

(1, 1, 4, 6)

- 배열의 슬라이싱

In [29]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l[:2]

[[1, 2, 3], [4, 5, 6]]

In [30]:
# 리스트에서는 행과 열로 동시에 슬라이싱이 안된다.
l[:2][1:]

[[4, 5, 6]]

In [32]:
c = np.arange(1, 10).reshape(3, 3)  # 1부터 9까지 3행과 3열로 출력
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
# 위에 두 행
c[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
# 오른쪽 두 열
c[:, 1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [35]:
# 5, 6, 8, 9
c[1:, 1:]

array([[5, 6],
       [8, 9]])

In [37]:
# 1, 4, 3, 6
c[:-1, ::2]

array([[1, 3],
       [4, 6]])

In [38]:
# 1, 7, 3, 9
c[::2, ::2]

array([[1, 3],
       [7, 9]])

- 연습 문제 2
    - 이 행렬에서 값 7 을 인덱싱한다.
    - 이 행렬에서 값 14 을 인덱싱한다.
    - 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
    - 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
    - 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.

In [39]:
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])

In [68]:
print(m[1, 2], m[2, 4], m[1, 1:3],       # m[2, 4] = m[-1, -1]
    m[1:, 2], m[:2, 3:], sep='\n')

7
14
[6 7]
[ 7 12]
[[3 4]
 [8 9]]


- 배열 인덱싱(Fancy indexing)

In [69]:
# idx 값이 True/False 이면 True 값이 있는 곳의 원소만 통과(Filter)
a = np.array([1,2,3,4,5,6,7,8,9,10])
idx = np.array([True,False,True,False,True,False,True,False,True,False])
a[idx]

array([1, 3, 5, 7, 9])

In [72]:
a % 2 == 1

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [71]:
a[idx] % 2 == 1

array([ True,  True,  True,  True,  True])

In [73]:
a[a % 2 == 1]

array([1, 3, 5, 7, 9])

In [75]:
# idx 값이 정수값(인덱스)이면 해당 인덱스의 원소가 선택됨
idx = np.array([1, 3, 5, 7, 9])
a[idx]

array([ 2,  4,  6,  8, 10])

- 연습 문제 3
    - 이 배열에서 3의 배수를 찾아라.
    - 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
    - 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

In [76]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [86]:
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [87]:
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [101]:
x[(x % 4 == 1) & (x % 3 == 0)]      # and는 사용할 수 없음

array([9])

In [105]:
# 위에서 구한 결과는 ndarray임. 원소의 밸류를 끄집어 내려면 다시 인덱싱 해줘야 함
x[8], x[(x % 3 == 0) & (x % 4 == 1)][0]

(9, 9)