### 3. 배열의 연산(Operation)

In [2]:
import numpy as np

- 벡터화 연산

In [3]:
x = np.arange(1, 101)
y = np.arange(1101, 1201)
z = x + y
z[:5]

array([1102, 1104, 1106, 1108, 1110])

In [4]:
z = 3 * x
z[:5]

array([ 3,  6,  9, 12, 15])

In [5]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [6]:
a > b

array([False, False,  True, False])

In [7]:
a / b

array([0.25, 1.  , 1.5 , 1.  ])

In [8]:
np.log(a), np.exp(a)

(array([0.        , 0.69314718, 1.09861229, 1.38629436]),
 array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003]))

In [9]:
c = np.arange(6).reshape(2, 3)
np.exp(c)

array([[  1.        ,   2.71828183,   7.3890561 ],
       [ 20.08553692,  54.59815003, 148.4131591 ]])

In [10]:
c + 3       # 모든 항에 3 덧셈

array([[3, 4, 5],
       [6, 7, 8]])

- 차원 축소 연산

In [11]:
x = np.arange(1, 5)
np.sum(x)               # numpy function

10

In [12]:
x.sum()                 # numpy 객체의 method

10

In [13]:
x.min(), x.max()

(1, 4)

In [14]:
# 대표값:
x.mean(), np.median(x)

(2.5, 2.5)

- all or any

In [15]:
np.all(np.array([True, False, True]))   # 모든 원소가 참이냐?

False

In [16]:
np.any(np.array([True, False, True]))   # 하나라도 참인 원소가 어디냐?

True

- 2차원 이상의 연산

In [17]:
a = np.arange(1, 7).reshape(2, 3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# 모든 원소의 합/평균
np.sum(a), np.mean(a)

(21, 3.5)

In [19]:
# 행 방향으로 합/평균
np.sum(a, axis=0), np.mean(a, axis=0)

(array([5, 7, 9]), array([2.5, 3.5, 4.5]))

In [20]:
# 열 방향으로 합/평균
np.sum(a, axis=1), np.mean(a, axis=1)

(array([ 6, 15]), array([2., 5.]))

- argmax, argmin

In [21]:
x = np.array([3, 12, 33, 9, 51, 26])
np.argmax(x), np.argmin(x)

(4, 0)

In [22]:
y = x.reshape(2, 3)
np.argmax(y, axis=0), np.argmin(y, axis=0)

(array([1, 1, 0], dtype=int64), array([0, 0, 1], dtype=int64))

- 연습 문제 3.3.1
    - 실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.
        - 전체의 최댓값
        - 각 행의 합
        - 각 행의 최댓값
        - 각 열의 평균
        - 각 열의 최솟값

In [23]:
x = np.arange(1., 31.).reshape(5, 6)
x

array([[ 1.,  2.,  3.,  4.,  5.,  6.],
       [ 7.,  8.,  9., 10., 11., 12.],
       [13., 14., 15., 16., 17., 18.],
       [19., 20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29., 30.]])

In [26]:
print(np.max(x),
np.sum(x, axis=1),
np.max(x, axis=1),
np.mean(x, axis=0),
np.min(x, axis=0))

30.0 [ 21.  57.  93. 129. 165.] [ 6. 12. 18. 24. 30.] [13. 14. 15. 16. 17. 18.] [1. 2. 3. 4. 5. 6.]


In [25]:
np.random.seed(2023)
np.set_printoptions(precision=4, suppress=True)
m = np.random.random(30).reshape(5, 6)
m

array([[0.322 , 0.8904, 0.5881, 0.1266, 0.1413, 0.4679],
       [0.0221, 0.7273, 0.5244, 0.5449, 0.4564, 0.5014],
       [0.3945, 0.1512, 0.3609, 0.1621, 0.338 , 0.1803],
       [0.391 , 0.0356, 0.5649, 0.2035, 0.3206, 0.3766],
       [0.1841, 0.104 , 0.4549, 0.1959, 0.3785, 0.9305]])

- 정렬

In [30]:
# np.sort() : 함수(a가 바뀌지 않음) / a.sort() : 메소드(a가 바뀜)
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
a

array([[ 4,  3,  5,  7],
       [ 1, 12, 11,  9],
       [ 2, 15,  1, 14]])

In [28]:
np.sort(a)          # axis=1 -> default

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [29]:
np.sort(a, axis=0)

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [33]:
a.sort()            # 자기 파괴적(in-place) method

In [32]:
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [34]:
a = np.array([[4, 3, 5, 7], [1, 12, 11, 9], [2, 15, 1, 14]])
j = np.argsort(a)                   # index 순서의 min -> max를 표현
j

array([[1, 0, 2, 3],
       [0, 3, 2, 1],
       [2, 0, 3, 1]], dtype=int64)

In [35]:
# 내림차순 정렬(열 방향)
np.sort(a)[:, ::-1]

array([[ 7,  5,  4,  3],
       [12, 11,  9,  1],
       [15, 14,  2,  1]])

In [51]:
# 내림차순 정렬(행 방향)
np.sort(a, axis=0)[::-1]

array([[ 4, 11, 14, 15],
       [ 2,  5,  9, 12],
       [ 1,  1,  3,  7]])

- 연습 문제 3.3.2
    - 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다.
    - 영어 성적을 기준으로 각 열(column)을 재정렬하라.

In [71]:
score = np.array([[1, 2, 3, 4], [46, 99, 100, 71], [81, 59, 90, 100]])
score

array([[  1,   2,   3,   4],
       [ 46,  99, 100,  71],
       [ 81,  59,  90, 100]])

In [74]:
a = np.argsort(score[1])
a

array([0, 3, 1, 2], dtype=int64)

In [76]:
a[::-1]

array([2, 1, 3, 0], dtype=int64)

In [77]:
score[:, a[::-1]]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])

In [78]:
score[:, (np.argsort(score[1])[::-1])]

array([[  3,   2,   4,   1],
       [100,  99,  71,  46],
       [ 90,  59, 100,  81]])