### 5. 난수 발생과 카운팅

In [1]:
import numpy as np

- Seed 설정

In [2]:
np.random.seed(2023)
np.random.random(5)

array([0.3219883 , 0.89042245, 0.58805226, 0.12659609, 0.14134122])

- 데이터의 순서 바꾸기

In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.random.shuffle(x)
x

array([7, 4, 3, 2, 8, 9, 1, 6, 0, 5])

- 데이터의 샘플링

In [5]:
np.random.choice(5, 5, replace=False)

array([3, 4, 0, 2, 1])

In [6]:
x = np.random.randint(1, 100, 10)
x

array([64, 49, 33, 30, 50, 50, 50, 50, 54, 39])

In [11]:
np.random.choice(x, 5, replace=False)

array([54, 30, 33, 39, 64])

- 난수 생성

In [13]:
# random() - Uniform 분포, 0 ~ 1 사이의 값
np.random.random(10)

array([0.75340344, 0.36581992, 0.61137308, 0.41961135, 0.09167672,
       0.53485392, 0.34076422, 0.01834099, 0.60345262, 0.92180617])

In [32]:
# randint(low, high, N) - [low, high)
np.random.randint(1, 7, 10)             # 1 에서부터 6 까지 10개를 가져옴

array([4, 5, 1, 3, 2, 2, 1, 1, 3, 5])

In [16]:
# normal(평균, 표준편차, N) - 정규분포
np.random.normal(170, 10, 10)

array([176.02016361, 162.29753898, 155.62308303, 183.50222845,
       172.71777366, 193.19401232, 170.45758874, 179.68127617,
       164.38753393, 193.93703726])

In [17]:
# randn(N) - 표준정규분포 N(0, 1)
np.random.randn(10)

array([-0.6382732 ,  0.34768965,  0.58710984,  0.36153521,  2.00216755,
        0.21146767,  0.43814089, -0.05984921,  1.35233252, -1.48563108])

In [27]:
# binomial(시도횟수, 평균, N) - 이항분포 B(N, p)
np.random.binomial(10, 0.5, 20).reshape(4, 5)

array([[5, 5, 6, 4, 3],
       [6, 3, 5, 8, 6],
       [4, 8, 5, 5, 7],
       [4, 3, 7, 5, 7]])

In [21]:
# 가설 검정: t - 검정
# standard_t(자유도, N)
np.random.standard_t(2, 10)

array([-4.73893668, -1.01840008, -1.78112333,  0.80712849, -1.31974138,
        1.83798133, -0.56053171,  0.51509713,  0.29185681, -0.2413877 ])

- 연습 문제 3.5.1
    - 동전을 10번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 가상 실험을 파이썬으로 작성한다.
    - 주사위를 100번 던져서 나오는 숫자의 평균을 구하라.

In [29]:
np.random.binomial(1, 0.5, 10)

array([0, 0, 0, 0, 0, 0, 1, 0, 0, 1])

In [40]:
np.random.randint(1, 7, 100).mean()

3.43

- 연습 문제 3.5.2
    - 가격이 10,000원인 주식이 있다.
    - 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자.
    - 250일 동안의 주가를 무작위로 생성하라

- 데이터 카운팅

In [41]:
dices = np.random.randint(1, 7, 100)
np.unique(dices)

array([1, 2, 3, 4, 5, 6])

In [45]:
indices, count = np.unique(dices, return_counts=True)
indices, count

(array([1, 2, 3, 4, 5, 6]), array([15, 18, 18, 18, 16, 15], dtype=int64))

In [48]:
indices * count

array([15, 36, 54, 72, 80, 90], dtype=int64)

In [49]:
np.sum(indices * count) / np.sum(count)

3.47

In [52]:
a = np.array(['a', 'b', 'c', 'b', 'a'])
indices, count = np.unique(a, return_counts=True)
indices, count

(array(['a', 'b', 'c'], dtype='<U1'), array([2, 2, 1], dtype=int64))

In [55]:

np.bincount(dices, minlength=6)

array([ 0, 15, 18, 18, 18, 16, 15], dtype=int64)