### 5. 난수 발생과 카운팅

In [1]:
import numpy as np

- Seed 설정

In [2]:
np.random.seed(2023)
np.random.random(5)

array([0.3219883 , 0.89042245, 0.58805226, 0.12659609, 0.14134122])

- 데이터의 순서 바꾸기

In [3]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.random.shuffle(x)
x

array([7, 4, 3, 2, 8, 9, 1, 6, 0, 5])

- 데이터의 샘플링

In [5]:
np.random.choice(5, 5, replace=False)

array([3, 4, 0, 2, 1])

In [6]:
x = np.random.randint(1, 100, 10)
x

array([64, 49, 33, 30, 50, 50, 50, 50, 54, 39])

In [11]:
np.random.choice(x, 5, replace=False)

array([54, 30, 33, 39, 64])

- 난수 생성

In [13]:
# random() - Uniform 분포, 0 ~ 1 사이의 값
np.random.random(10)

array([0.75340344, 0.36581992, 0.61137308, 0.41961135, 0.09167672,
       0.53485392, 0.34076422, 0.01834099, 0.60345262, 0.92180617])

In [15]:
# randint(low, high, N) - [low, high)
np.random.randint(1, 7, 10)             # 1 에서부터 7 까지 10개를 가져옴

array([1, 2, 5, 4, 3, 3, 1, 1, 6, 6])

In [16]:
# normal(평균, 표준편차, N) - 정규분포
np.random.normal(170, 10, 10)

array([176.02016361, 162.29753898, 155.62308303, 183.50222845,
       172.71777366, 193.19401232, 170.45758874, 179.68127617,
       164.38753393, 193.93703726])

In [17]:
# randn(N) - 표준정규분포 N(0, 1)
np.random.randn(10)

array([-0.6382732 ,  0.34768965,  0.58710984,  0.36153521,  2.00216755,
        0.21146767,  0.43814089, -0.05984921,  1.35233252, -1.48563108])

In [20]:
# binomial(시도횟수, 평균, N) - 이항분포 B(N, p)
np.random.binomial(10, 0.5, 20).reshape(4, 5)


array([[5, 5, 4, 4, 4],
       [4, 4, 5, 3, 6],
       [6, 5, 6, 6, 6],
       [6, 6, 5, 7, 5]])