1. Series

In [97]:
import numpy as np
import pandas as pd

- Series 생성
    - numpy 1차원 어레이 + index

In [98]:
s = pd.Series([9904312, 3448737, 2890451, 2466052],
              index=["서울", "부산", "인천", "대구"])
s

서울    9904312
부산    3448737
인천    2890451
대구    2466052
dtype: int64

In [99]:
type(s)

pandas.core.series.Series

In [100]:
# 인덱스를 별도로 설정하지 않으면, 인덱스는 0, 1, 2, ... 이 된다.
pd.Series(np.arange(10, 15))

0    10
1    11
2    12
3    13
4    14
dtype: int32

In [101]:
s.index, type(s.index)

(Index(['서울', '부산', '인천', '대구'], dtype='object'),
 pandas.core.indexes.base.Index)

In [102]:
s.values, type(s.values)

(array([9904312, 3448737, 2890451, 2466052], dtype=int64), numpy.ndarray)

In [103]:
s.name = '인구'
s.index.name = '도시'
s

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

- 연산(Operation)

In [104]:
s / 1000000

도시
서울    9.904312
부산    3.448737
인천    2.890451
대구    2.466052
Name: 인구, dtype: float64

- 인덱싱

In [105]:
s['부산'], s[1], s.부산                 # 결과는 scalar

(3448737, 3448737, 3448737)

In [106]:
s['대구'], s[3], s[-1], s.대구

(2466052, 2466052, 2466052, 2466052)

In [107]:
s[[0, 1]]                       # 결과는 Series

도시
서울    9904312
부산    3448737
Name: 인구, dtype: int64

In [108]:
s[['서울', '부산']]             # 반드시 list 형태로 들어와줘야함

도시
서울    9904312
부산    3448737
Name: 인구, dtype: int64

In [109]:
s[(s > 2500000) & (s < 5000000)]    # 250만 초과 500만 미만

도시
부산    3448737
인천    2890451
Name: 인구, dtype: int64

In [110]:
s[s > 5000000]

도시
서울    9904312
Name: 인구, dtype: int64

- 슬라이싱

In [111]:
# 숫자 인덱스로 하는 슬라이싱은 넘파이와 동일
s[:2]

도시
서울    9904312
부산    3448737
Name: 인구, dtype: int64

In [112]:
# 인덱스 문자열로 하는 경우에는 : 뒤 인덱스를 포함
s['서울':'인천']

도시
서울    9904312
부산    3448737
인천    2890451
Name: 인구, dtype: int64

- 시리즈와 딕셔너리

In [113]:
'서울' in s

True

In [114]:
for k, v in s.items():
    print(f'{k}: {v}')

서울: 9904312
부산: 3448737
인천: 2890451
대구: 2466052


In [115]:
d = {"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158}
s2 = pd.Series(d)
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

In [116]:
# 순서를 정하고 싶으면, 인덱스를 별도로 설정해야 함
s2 = pd.Series(d, index=['서울','부산','인천','대전'])
s2

서울    9631482
부산    3393191
인천    2632035
대전    1490158
dtype: int64

- 인덱스 기반 연산

In [117]:
ds = s - s2
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [118]:
ds.notnull()

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [119]:
ds[ds.notnull()]

부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [120]:
rs = (s - s2) / s2 * 100
rs = rs[rs.notnull()]
rs

부산    1.636984
서울    2.832690
인천    9.818107
dtype: float64

- 데이터의 갱신, 추가, 삭제

In [121]:
rs['부산'] = 1.64
rs[1] = 2.83
rs.인천 = 9.82
rs

부산    1.64
서울    2.83
인천    9.82
dtype: float64

In [122]:
rs['대구'] = 1.41
rs

부산    1.64
서울    2.83
인천    9.82
대구    1.41
dtype: float64

In [123]:
del rs['인천']          # rs.인천, rs[2] 는 사용할 수 없음
rs

부산    1.64
서울    2.83
대구    1.41
dtype: float64

- 연습 문제 4.1.1
    - 임의로 두 개의 시리즈 객체를 만든다.
    - 모두 문자열 인덱스를 가져야 하며 두 시리즈에 공통적으로 포함되지 않는 라벨이 있어야 한다.
    - 위에서 만든 두 시리즈 객체를 이용하여 사칙 연산을 한다.

In [124]:
e = pd.Series([5706, 2307, 256, 5783],
              index=["a", "b", "c", "d"])
f = pd.Series([2146, 212, 57, 1246],
              index=["x", "b", "c", "d"])
e, f

(a    5706
 b    2307
 c     256
 d    5783
 dtype: int64,
 x    2146
 b     212
 c      57
 d    1246
 dtype: int64)

In [125]:
e - f, e + f, e * f, e / f

(a       NaN
 b    2095.0
 c     199.0
 d    4537.0
 x       NaN
 dtype: float64,
 a       NaN
 b    2519.0
 c     313.0
 d    7029.0
 x       NaN
 dtype: float64,
 a          NaN
 b     489084.0
 c      14592.0
 d    7205618.0
 x          NaN
 dtype: float64,
 a          NaN
 b    10.882075
 c     4.491228
 d     4.641252
 x          NaN
 dtype: float64)

- 중요한 method

In [126]:
dice = pd.Series(np.random.randint(1, 7, 10))
dice

0    2
1    3
2    4
3    4
4    4
5    2
6    5
7    1
8    3
9    6
dtype: int32

In [127]:
# element의 갯수
dice.count()

10

In [128]:
# 고유한 값
dice.unique()

array([2, 3, 4, 5, 1, 6])

In [129]:
# 고유한 값의 갯수
dice.nunique()

6

In [130]:
# 고유한 값 별로 갯수
dice.value_counts()

4    3
2    2
3    2
5    1
1    1
6    1
Name: count, dtype: int64

In [131]:
np.unique(dice.values, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([1, 2, 2, 3, 1, 1], dtype=int64))

In [132]:
dice.min(), dice.max(), dice.sum(), dice.mean()

(1, 6, 34, 3.4)

In [133]:
# 요약 기술통계
dice.describe()

count    10.000000
mean      3.400000
std       1.505545
min       1.000000
25%       2.250000
50%       3.500000
75%       4.000000
max       6.000000
dtype: float64

In [134]:
# sort
dice.sort_values()

7    1
0    2
5    2
1    3
8    3
2    4
3    4
4    4
6    5
9    6
dtype: int32

In [136]:
# 데이터 기준 오름차순
s.sort_values()

도시
대구    2466052
인천    2890451
부산    3448737
서울    9904312
Name: 인구, dtype: int64

In [137]:
# 데이터 기준 내림차순
s.sort_values(ascending=False)

도시
서울    9904312
부산    3448737
인천    2890451
대구    2466052
Name: 인구, dtype: int64

In [138]:
# 인덱스 기준 오름차순
s.sort_index()

도시
대구    2466052
부산    3448737
서울    9904312
인천    2890451
Name: 인구, dtype: int64

In [139]:
# 인덱스 기준 내림차순
s.sort_index(ascending=False)

도시
인천    2890451
서울    9904312
부산    3448737
대구    2466052
Name: 인구, dtype: int64

In [141]:
# implace 옵션을 True로 하면 자기파괴적 메소드가 됨
s.sort_index(inplace=True)
s

도시
대구    2466052
부산    3448737
서울    9904312
인천    2890451
Name: 인구, dtype: int64

- 결측치(Na, NaN, Null) 처리

In [142]:
ds

대구         NaN
대전         NaN
부산     55546.0
서울    272830.0
인천    258416.0
dtype: float64

In [143]:
ds.isna()

대구     True
대전     True
부산    False
서울    False
인천    False
dtype: bool

In [144]:
ds.isnull()

대구     True
대전     True
부산    False
서울    False
인천    False
dtype: bool